# Generated by Django 4.0.3 on 2022-03-15 21:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Switches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.URLValidator])),
                ('username', models.CharField(max_length=255)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('port', models.CharField(max_length=20)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.switches')),
            ],
            options={
                'unique_together': {('switch', 'port')},
            },
        ),
        migrations.CreateModel(
            name='DataPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.DurationField()),
                ('bytes', models.BigIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ports')),
            ],
        ),
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('ssh', 'SSH'), ('telnet', 'Telnet')], max_length=10)),
                ('port', models.IntegerField()),
                ('priority', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)])),
                ('query', models.CharField(max_length=255)),
                ('query_unit', models.CharField(choices=[('full', 'Auto (Full: bytes)'), ('short', 'Auto (Short: B)'), ('GB', 'Gigabytes'), ('Gb', 'Gigabits'), ('MB', 'Megabytes'), ('Mb', 'Megabits'), ('KB', 'Kilobytes'), ('Kb', 'Kilobits'), ('B', 'Bytes'), ('b', 'Bits')], max_length=255)),
                ('query_regex', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator])),
                ('query_end', models.CharField(blank=True, max_length=255)),
                ('login_prompt', models.CharField(blank=True, max_length=255)),
                ('password_prompt', models.CharField(blank=True, max_length=255)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.switches')),
            ],
            options={
                'unique_together': {('switch', 'priority')},
            },
        ),
    ]
