# Generated by Django 4.0.3 on 2022-03-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='query_unit',
            field=models.CharField(choices=[('auto', 'Auto'), ('GB', 'Gigabytes'), ('Gb', 'Gigabits'), ('MB', 'Megabytes'), ('Mb', 'Megabits'), ('KB', 'Kilobytes'), ('Kb', 'Kilobits'), ('B', 'Bytes'), ('b', 'Bits')], help_text='The unit to be expected from the query.', max_length=10),
        ),
    ]
